### ISSUE TITLE
Locatie ID asociatie

### ISSUE THREAD

**Issue by cybuletz** [cnecrea/e-bloc#2]
Salut,
Ma chinui de jumatate de ora sa gasesc ID-ul asociatiei fara succes. 
Ar fi util un screenshot sau ceva mai multe detalii cu locatia exacta a acestui ID.

**Comment by gheorghegeorgiu** [comment]
In aplicatia e-bloc, meniu>setari>acces asociatii

**Comment by gheorghegeorgiu** [comment]
> Salut, Ma chinui de jumatate de ora sa gasesc ID-ul asociatiei fara succes. Ar fi util un screenshot sau ceva mai multe detalii cu locatia exacta a acestui ID.

In aplicatia e-bloc, meniu>setari>acces asociatii

**Comment by cybuletz** [comment]
acolo este doar ID de client, nu al asociatiei

**Comment by cybuletz** [comment]
![Screenshot_2024-12-31-17-14-04-823_com xisoft ebloc ro-edit](https://github.com/user-attachments/assets/b76a0ad2-92de-4206-b89b-598d6f9529b9)

**Comment by cnecrea** [comment]
Te loghezi pe pagina, rulezi inspectare, te duci la Network, filtrezi dupa INDEX si faci click dreapta, apoi Copy -> Copy all listed as cURL

<img width="1709" alt="image" src="https://github.com/user-attachments/assets/96ec05b8-a4f4-4997-8f29-94e599e9b05b" />


Te duci apoi pe https://curlconverter.com/, si dai paste. Sus, gasesti cookies. Exemplu:

```yaml
cookies = {
    'username': 'email@exemplu.com',
    'asoc-cur': 'XXXXX',
    'avizier-luna-cur': '-',
    'facturi-luna-cur': '-',
    'index-luna-cur': '-',
    **'home-ap-cur': 'XXXXX_XX',**
    'home-stat-cur': '6',
    'PHPSESSID': '4kh25v0ua12r973i10ug06sspo',
}
```
    'asoc-cur': 'XXXXX', = asociatie
    **'home-ap-cur': 'XXXXX_XX',** = asociatie _ ID apartament
