### ISSUE TITLE
Schimbare nume attribute la senzori

### ISSUE THREAD

**Issue by zauan** [cnecrea/e-bloc#4]
Salutare,

in primul rand, felicitari pentru integrare. Am instalat-o si am observat ca sunt ceva probleme cand incerci sa folosesti attributele senzorilor direct in dashboard. Din ce observ, problema este ca attributele nu sunt separate prin "_".

De exemplu:

`"Nivel restanță": data.get("nivel_restanta", "Necunoscut"),`

ar trebui sa fie

`"nivel_restanta": data.get("nivel_restanta", "Necunoscut"),`

Practic, spatiile trebuie inlocuite cu "_"

Ca si afisare, in home assistant se vor afisa corect, plusul fiind ca vei putea sa folosesti atributele direct in dashboard ( de exemplu, folosind bubble card )

**Comment by cnecrea** [comment]
Salut,

Mersi pentru feedback.

Ceea ce spui este fals. Atributele pot fi preluate indiferent dacă conțin spații, caractere cu diacritice etc.

Aici îți dau un exemplu de cum poți adăuga datele clientului:

```yaml
type: entities
title: Informații client
entities:
  - type: attribute
    entity: sensor.date_client
    attribute: Cod client
    name: Cod client
  - type: attribute
    entity: sensor.date_client
    attribute: Apartament
    name: Apartament
  - type: attribute
    entity: sensor.date_client
    attribute: Persoane declarate
    name: Persoane declarate
  - type: attribute
    entity: sensor.date_client
    attribute: Restanță de plată
    name: Restanță de plată
  - type: attribute
    entity: sensor.date_client
    attribute: Ultima zi de plată
    name: Ultima zi de plată
  - type: attribute
    entity: sensor.date_client
    attribute: Contor trimis
    name: Contor trimis
  - type: attribute
    entity: sensor.date_client
    attribute: Începere citire contoare
    name: Începere citire contoare
  - type: attribute
    entity: sensor.date_client
    attribute: Încheiere citire contoare
    name: Încheiere citire contoare
  - type: attribute
    entity: sensor.date_client
    attribute: Luna cu datoria cea mai veche
    name: Luna cu datoria cea mai veche
  - type: attribute
    entity: sensor.date_client
    attribute: Luna afișată
    name: Luna afișată
  - type: attribute
    entity: sensor.date_client
    attribute: Nivel restanță
    name: Nivel restanță
```

Mai jos, altul despre index

```yaml
type: entities
title: Index contor
entities:
  - type: attribute
    entity: sensor.index_contor
    attribute: Index vechi
    name: Index vechi
  - type: attribute
    entity: sensor.index_contor
    attribute: Index nou
    name: Index nou

```

După cum observi, nu este vorba de spațiu sau alte caractere, ci de modul în care îți formezi cardul. Sper să îți fie de folos


---

### 💡 Contribuie la dezvoltare

Îți place această integrare? **Arată-ți aprecierea!** 🎉  
O simplă invitație la o cafea poate face diferența și susține viitoarele actualizări. ☕  

[![Buy Me A Coffee](https://img.shields.io/badge/Buy%20Me%20A%20Coffee-Contribuie%20la%20dezvoltare-orange?style=for-the-badge&logo=buy-me-a-coffee)](https://buymeacoffee.com/cnecrea)

Mulțumesc pentru sprijinul tău, ajută enorm! 🙌

**Comment by zauan** [comment]
Salut!

Inseamna ca nu merge cu bubble card doar. Cam asta folosesc pentru tot dashboardul :). Am modificat manual extensia ca sa imi mearga

**Comment by cnecrea** [comment]
> Salut!
> 
> Inseamna ca nu merge cu bubble card doar. Cam asta folosesc pentru tot dashboardul :). Am modificat manual extensia ca sa imi mearga

Dacă îmi spui ce tip de entitate folosești pentru Bubble Card, probabil te pot ajuta. Trebuie să văd detaliile. (Nu folosesc Bubble Card decât pentru separatoare, deci nu îl cunosc foarte bine)


---

### 💡 Contribuie la dezvoltare

Îți place această integrare? **Arată-ți aprecierea!** 🎉  
O simplă invitație la o cafea poate face diferența și susține viitoarele actualizări. ☕  

[![Buy Me A Coffee](https://img.shields.io/badge/Buy%20Me%20A%20Coffee-Contribuie%20la%20dezvoltare-orange?style=for-the-badge&logo=buy-me-a-coffee)](https://buymeacoffee.com/cnecrea)

Mulțumesc pentru sprijinul tău, ajută enorm! 🙌

**Comment by zauan** [comment]
Pentru mine e ok.. am rezolvat modificand extensia ta si adaugand _ in loc de spatii.

cam asa arata configuratia cardului cu integrarea "fixata":

<img width="1051" alt="Image" src="https://github.com/user-attachments/assets/4396132e-fac5-4c26-9e17-be325eb53ee8" />

Folosind spatii, aveam erori de JS in consola si nu mergea.

Dupa cum vezi, Home assistant stie sa faca convert la atribut cand il afiseaza, inlocuid "_" cu spatiu si facand uppercase la primul cuvant.

P.s. pot sa fac un pull request cu modificarile daca vrei

**Comment by cnecrea** [comment]
Nu așa. După cum vezi, o imagine nu îmi este de folos.

Arată-mi un exemplu de cod.
Nu uita să folosești următorul format pentru a afișa codul corect pe GitHub, adică să incluzi COD, COD, COD între delimitatorii de mai jos:

<pre>
```yaml
COD
COD
COD
```
</pre>

---

### 💡 Contribuie la dezvoltare

Îți place această integrare? **Arată-ți aprecierea!** 🎉  
O simplă invitație la o cafea poate face diferența și susține viitoarele actualizări. ☕  

[![Buy Me A Coffee](https://img.shields.io/badge/Buy%20Me%20A%20Coffee-Contribuie%20la%20dezvoltare-orange?style=for-the-badge&logo=buy-me-a-coffee)](https://buymeacoffee.com/cnecrea)

Mulțumesc pentru sprijinul tău, ajută enorm! 🙌

**Comment by zauan** [comment]
asta e codul de mai jos. Ca si varianta, se puteau pune ghilimele la "attribute" si probabil ca mergea si cu spatii, doar ca nu merge configurat din dashboard ci doar din yaml

``` yaml
type: custom:bubble-card
card_type: button
button_type: state
entity: sensor.date_client
show_attribute: true
attribute: restanta_de_plata
show_state: false
name: Restanta de plata
```

**Comment by cnecrea** [comment]
Ca remarcă, după cum observi, folosești o entitate de tip toggle (switch, light etc.), ceea ce, din start, este incorect. Acest lucru arată că Bubble Card nu suportă direct „atribute”, dar funcționează corect cu senzori normali.

**Ceea ce încerci să faci e ca și cum ai încerca să împrietenești focul cu apa.**

Dacă dorești să afișezi, de exemplu, restanța de plată, îți recomand să creezi un senzor suplimentar folosind template sensor. Astfel, nu vei avea probleme în viitor, mai ales când vor fi aduse actualizări. Aceasta este cea mai corectă metodă pentru a lucra cu Bubble Card, având în vedere că nu suportă direct atribute.


```yaml
sensor:
  - platform: template
    sensors:
      nivel_restanta:
        friendly_name: "Nivel restanță"
        value_template: "{{ state_attr('sensor.date_client', 'Nivel restanță') }}"
```

Și apoi, poți folosi bubble-card:

```yaml
type: custom:bubble-card
card_type: button
button_type: state
entity: sensor.nivel_restanta
name: Nivel restanță
show_icon: true
show_name: true
sub_button:
  - entity: sensor.nivel_restanta
    show_background: false
    show_state: true
    name: Nivel restanță
    icon: mdi:account
````

Te rog ca pe viitor să te documentezi despre integrări, carduri și teme. Cu puțin research, vei ajunge la concluzii clare și vei evita munca inutilă.

---

### 💡 Contribuie la dezvoltare

Îți place această integrare? **Arată-ți aprecierea!** 🎉  
O simplă invitație la o cafea poate face diferența și susține viitoarele actualizări. ☕  

[![Buy Me A Coffee](https://img.shields.io/badge/Buy%20Me%20A%20Coffee-Contribuie%20la%20dezvoltare-orange?style=for-the-badge&logo=buy-me-a-coffee)](https://buymeacoffee.com/cnecrea)

Mulțumesc pentru sprijinul tău, ajută enorm! 🙌
